// AUTO-GENERATED by scripts/gen-assets.mjs (runs before dev/build). Do not edit.
export const PUBLIC_IMAGES: ReadonlySet<string> = new Set([
  "/icon-192.png",
  "/icon-512.png",
  "/images/intro-logo.webp",
  "/images/profile.jpg",
  "/images/profile.webp",
  "/og-image.png"
]);
