// Lists image files under public/ so components can skip requests for images that don't exist
// (no 404s in the console; the placeholder renders immediately). Runs before `dev` and `build`.
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const PUBLIC = "public";
const IMAGE = /\.(png|jpe?g|webp|avif|gif|svg)$/i;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : IMAGE.test(name) ? ["/" + relative(PUBLIC, full).split(sep).join("/")] : [];
  });
}

const files = walk(PUBLIC).sort();
writeFileSync(
  "lib/assets.generated.ts",
  `// AUTO-GENERATED by scripts/gen-assets.mjs (runs before dev/build). Do not edit.\n` +
    `export const PUBLIC_IMAGES: ReadonlySet<string> = new Set(${JSON.stringify(files, null, 2)});\n`,
);
console.log(`gen-assets: ${files.length} images indexed`);
